company/api/urls.py
from django.conf.urls import url

from company.api import views


urlpatterns = [
    url(r'^user/(?P<pk>\d+)/$', views.UserDetailAPIView.as_view(), name='api-user-detail'),

    url(r'^companies/create/$', views.CompanyCreateAPIView.as_view(),
        name='api-companies-create'),
    url(r'^companies/list/$', views.CompaniesListAPIView.as_view(),
        name='api-companies-list'),
    
    url(r'^companies/detail/(?P<pk>\d+)/$',
        views.CompaniesDetailAPIView.as_view(), 
        name='api-companies-detail'),
    
    url(r'^companies/update/(?P<pk>\d+)/$',
        views.CompaniesUpdateAPIView.as_view(), name='api-companies-list'),
    url(r'^companies/delete/(?P<pk>\d+)/$',
        views.CompaniesDeleteAPIView.as_view(), name='api-companies-list'),
    

    url(r'^jobs/detail/(?P<pk>\d+)/$',
        views.JobsDetailAPIView.as_view(), 
        name='api-jobs-detail'),

    url(r'^jobs/list/$', views.JobsListAPIView.as_view(), name='api-jobs-list'),

]

company/urls.py
from django.conf.urls import url

from company import views


urlpatterns = [

    url(r'^register/$', views.RegisterCBV.as_view(), name='register'),
    
    url(r'^login/$', views.LoginCBV.as_view(), name='login'),
    url(r'^dashboard/$', views.DashboardCBV.as_view(), name='dashboard'),
    url(r'^search/$', views.SearchCBV.as_view(), name='search'),

    url(r'^job/new/$', views.NewJobCBV.as_view(), name='newJob'),
    url(r'^job/detail/(?P<pk>\d+)/$', views.JobDetailCBV.as_view(), name='jobDetail'),
    url(r'^job/edit/(?P<pk>\d+)/$', views.JobEditCBV.as_view(), name='jobEdit'),
    url(r'^job/delete/(?P<pk>\d+)/$', views.JobDeleteCBV.as_view(), name='jobDelete'),

    url(r'^profile/create/$', views.ProfileCreateCBV.as_view(), name='profileCreate'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileCBV.as_view(), name='profile'),
    url(r'^profile/delete/(?P<pk>\d+)/$', views.ProfileDeleteCBV.as_view(), name='profileDelete'),

    url(r'^settings/$', views.SettingsCBV.as_view(), name='settings'),
    url(r'^logout/$', views.LogoutCBV.as_view(), name='logout'),

]

portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.documentation import include_docs_urls

from company.views import IndexViewCBV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexViewCBV.as_view(), name='index'),
    url(r'^company/', include('company.urls')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('company.api.urls', namespace='api-companies')),

    url(r'^docs/', include_docs_urls(title='My API title'))

]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

company/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_delete, post_save

from company.receivers import post_delete_jobs, post_save_jobs
from company.utils import max_string_length, generate_id, user_directory_path
from company.managers import DefaultManager, SqliteManager


# Monkey patching User model
User = settings.AUTH_USER_MODEL


class Jobs(models.Model):

    job_type_choices = (
                        ('I', 'Internship'),
                        ('T', 'Temporary'),
                        ('C', 'Contract'),
                        ('P', 'Permanant'),
                        ('O', 'Other'),
                       )

    job_salary_choices = (
                            ('ASP', 'As per standard'),
                            ('0', '< 1,00,000'),
                            ('1', '1,00,000 to 2,99,999'),
                            ('3', '3,00,000 to 5,99,999'),
                            ('6', '6,00,000 to 9,99,999'),
                            ('10', '10,00,000 +'),
                          )

    job_id = models.CharField(max_length=max_string_length, 
                                verbose_name="Job Id", default=generate_id)
    job_company_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Posted by company")  # foreign key of company
    job_title = models.CharField(max_length=256, verbose_name="Job Title")
    job_location = models.CharField(max_length=256, verbose_name="Job Location")
    job_type = models.CharField(max_length=1, choices=job_type_choices, verbose_name="Job Type", default="I")
    job_salary = models.CharField(max_length=3, choices=job_salary_choices, verbose_name="Salary", default="ASP")
    job_starting_date = models.CharField(default="ASAP", max_length=256, verbose_name="Joining Date")
    job_date_posted = models.DateTimeField(auto_now_add=True, verbose_name="Date Posted")

    objects = DefaultManager()
    sqlite = SqliteManager()


    def __str__(self):
        return self.job_title


    def get_absolute_url(self):
        return reverse('jobDetail', kwargs={'pk': self.pk})


    class Meta:
        verbose_name = "Job"
        verbose_name_plural = "Jobs"
        ordering = ["-job_date_posted"]


class Companies(models.Model):
    company_id = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    company_logo = models.FileField(upload_to=user_directory_path, blank=True, null=True, verbose_name="Company Logo")
    company_name = models.CharField(max_length=256, verbose_name="Company Name")
    company_address = models.TextField(verbose_name="Company Address")
    company_email = models.CharField(max_length=256, verbose_name="Company Email Id")
    company_contact = models.IntegerField(verbose_name="Company Contact")

    objects = DefaultManager()
    sqlite = SqliteManager()

    def __str__(self):
        return self.company_name


    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"
        permissions = (
                        ("FE_add_job", "Can add new jobs"),
                        ("FE_detail_job", "Can see the details of a job"),
                        ("FE_update_job", "Can change the jobs"),
                        ("FE_delete_jobs", "Can delete a job"),
                      )


post_save.connect(post_save_jobs, sender=Jobs)
post_delete.connect(post_delete_jobs, sender=Jobs)

company/api/views.py
from django.contrib.auth.models import User
from rest_framework.generics import (CreateAPIView, ListAPIView,
									RetrieveAPIView, UpdateAPIView, DestroyAPIView)

from company.api.serializers import JobSerializer, CompanySerializer, UserSerializer
from company.models import Jobs, Companies


class CompanyCreateAPIView(CreateAPIView):
    queryset = Companies.objects.all()
    serializer_class = CompanySerializer

    def perform_create(self, serializer):
        serializer.save(company_id=self.request.user)


class CompaniesListAPIView(ListAPIView):
    queryset = Companies.objects.all()
    serializer_class = CompanySerializer


class CompaniesDetailAPIView(RetrieveAPIView):
    queryset = Companies.objects.all()
    serializer_class = CompanySerializer
    lookup_field = 'pk'
    # lookup_url_kwarg = 'company_name'


class CompaniesUpdateAPIView(UpdateAPIView):
    queryset = Companies.objects.all()
    serializer_class = CompanySerializer


class CompaniesDeleteAPIView(DestroyAPIView):
    queryset = Companies.objects.all()
    serializer_class = CompanySerializer


class JobsListAPIView(ListAPIView):
    queryset = Jobs.objects.all()
    serializer_class = JobSerializer


class JobsDetailAPIView(RetrieveAPIView):
    queryset = Jobs.objects.all()
    serializer_class = JobSerializer


class UserDetailAPIView(RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

company/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib import messages

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse

from django.urls import reverse_lazy

from django.views.generic import (TemplateView, ListView, DetailView, FormView, 
                                    CreateView, UpdateView, DeleteView, RedirectView)

from company.models import Jobs, Companies
from company.mixins import LoginRequiredMixin, IsOwnerOrNoAccess
from company.forms import (UserCreateForm, LoginForm, ChangePassForm, 
                            NewJobForm, CompanyForm, SearchForm)

from django.contrib.auth.mixins import PermissionRequiredMixin

from django.http import HttpResponseRedirect


class IndexViewCBV(TemplateView):
    template_name = 'index.html'


class RegisterCBV(CreateView):
    model = User
    template_name = "company/register.html"
    form_class = UserCreateForm
    success_url = reverse_lazy('login')


    def get_form_kwargs(self):
        kwargs = super(RegisterCBV, self).get_form_kwargs()
        kwargs['data'] = self.request.POST or None
        kwargs['help_text'] = False
        return kwargs


class LoginCBV(FormView):
    template_name = "company/login.html"
    form_class = LoginForm


    def get_success_url(self):
        return reverse('dashboard')


    def get_form_kwargs(self):
        kwargs = super(LoginCBV, self).get_form_kwargs()
        kwargs['data'] = self.request.POST or None
        # kwargs['user'] = self.request.user
        return kwargs


    def form_valid(self, form):

        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = auth.authenticate(username=username, password=password)
        auth.login(self.request, user)

        if self.next:
            return redirect(self.next)
        else:
            return redirect(self.get_success_url())


    def post(self, request, *args, **kwargs):

        form = self.get_form()

        self.next = request.GET.get("next")

        if request.user.is_authenticated:

            if self.next:
                return redirect(self.next)
            else:
                return redirect('dashboard')        

        if form.is_valid():
            return self.form_valid(form)
        else: 
            return self.form_invalid(form)


class DashboardCBV(LoginRequiredMixin, TemplateView):
    template_name = "company/dashboard.html"


    def get_context_data(self, **kwargs):
        context = super(DashboardCBV, self).get_context_data(**kwargs)
               
        context['count'] = Jobs.objects.filter(job_company_id=self.request.user.pk).count()
        context['applicants'] = "00"
        context['shortlisted'] = "00"
        context['joining'] = "00"

        return context


class SearchCBV(LoginRequiredMixin, ListView):
    template_name = "company/search.html"
    model = Jobs
    paginate_by = 3
    context_object_name = 'jobs'


    def get_queryset(self):
        jobs = Jobs.objects.filter(job_company_id=self.request.user.pk)

        # get search parameters from the request if any
        job_title = self.request.GET.get("job_title", '')
        job_location = self.request.GET.get("job_location", '')

        # default value is set to "-" in front end and backend 
        # to enable allowing to send empty values with no default
        job_type = self.request.GET.get("job_type", '-')
        job_salary = self.request.GET.get("job_salary", '-')
        
        # filter the jobs posted by the current company according to the search parameters
        if job_title != "":
            jobs = jobs.filter(job_title__icontains=job_title)

        if job_location != "":
            jobs = jobs.filter(job_location__iexact=job_location)

        # using for loop here only to make sure that 
        # the choices options are in a centralised location i.e. in the Jobs model
        for job in Jobs.job_type_choices:
            if job_type == job[0]:
                jobs = jobs.filter(job_type__iexact=job_type)
                break

        for salary in Jobs.job_salary_choices:
            if job_salary == salary[0]:
                jobs = jobs.filter(job_salary__iexact=job_salary)
                break

        for job in jobs:
            job.job_type = job.get_job_type_display()
            job.job_salary = job.get_job_salary_display()

        return jobs


    def get_context_data(self, **kwargs):
        context = super(SearchCBV, self).get_context_data(**kwargs)
       
        # context['count'] = self.get_queryset.count()
        context['count'] = len(context["jobs"])

        return context


class NewJobCBV(LoginRequiredMixin, CreateView):
    template_name = 'company/job.html'
    form_class = NewJobForm
    success_url = reverse_lazy('newJob')

    def form_valid(self, form):
        form.instance.job_company_id = self.request.user
        self.object = form.save()
        messages.success(self.request, "You have successfully posted a new job.")
        return redirect(self.get_success_url())


class JobDetailCBV(LoginRequiredMixin, IsOwnerOrNoAccess, DetailView):
    model = Jobs
    template_name = 'company/jobDetail.html'
    context_object_name = "job"
    
    no_permission_redirect_url = "dashboard"
    permission_denied_message = "You don't have permission to view this job."
    owner_field = "job_company_id"

    def get_object(self, queryset=None):
        obj = super(JobDetailCBV, self).get_object(queryset=queryset)
        obj.job_type = obj.get_job_type_display()
        obj.job_salary = obj.get_job_salary_display()
        return obj


class JobEditCBV(LoginRequiredMixin, IsOwnerOrNoAccess, UpdateView):
    model = Jobs
    template_name = 'company/jobEdit.html'
    form_class = NewJobForm
    success_url = reverse_lazy('search')

    no_permission_redirect_url = "dashboard"
    no_permission_error_message = "You don't have permission to edit this job."
    owner_field = "job_company_id"


class JobDeleteCBV(LoginRequiredMixin, IsOwnerOrNoAccess, DeleteView):
    model = Jobs
    success_url = reverse_lazy('search')
    
    no_permission_redirect_url = "dashboard"
    no_permission_error_message = "You don't have permission to delete this job."
    owner_field = "job_company_id"


class ProfileCBV(LoginRequiredMixin, TemplateView):
    template_name = 'company/profile.html'
    model = Companies
    context_object_name = "profile"


    def get(self, request, *args, **kwargs):
        
        try: 
            profile = Companies.objects.get(pk=request.user.pk) 
        except ObjectDoesNotExist:
            return redirect('profileCreate')

        context = {}
        context['profile'] = profile.__dict__
        
        return render(request, self.template_name, context)


class ProfileCreateCBV(LoginRequiredMixin, CreateView):
    template_name = 'company/profileCreate.html'
    form_class = CompanyForm
    model = Companies


    def get_success_url(self, **kwargs):
        return reverse("profile", kwargs={'pk': self.request.user.pk})


    def get_form_kwargs(self, **kwargs):
        kwargs = super(ProfileCreateCBV, self).get_form_kwargs(**kwargs)
        kwargs['initial'] = {'company_id': self.request.user.pk}
        return kwargs


class ProfileDeleteCBV(LoginRequiredMixin, DeleteView):
    model = Companies
    success_url = reverse_lazy('profileCreate')


class SettingsCBV(LoginRequiredMixin, FormView):
    template_name = 'company/settings.html'
    form_class = ChangePassForm
    success_url = reverse_lazy("settings")


    def get_form_kwargs(self):
        kwargs = super(SettingsCBV, self).get_form_kwargs()
        kwargs['data'] = self.request.POST or None
        kwargs['user'] = self.request.user
        return kwargs


    def form_valid(self, form):

        try:
            user = self.request.user
            new_password = form.cleaned_data.get("new_password")
            user.set_password('{}'.format(new_password))
            user.save()

            # if we dont call this function user will be logged out after password is changed.
            auth.update_session_auth_hash(self.request, user)

            messages.success(self.request, "You have successfully changed your password.")

        except Exception:
            messages.error(self.request,
                           "Something went wrong, we could not change your password. Please try again.")

        return super(SettingsCBV, self).form_valid(form)


    def get(self, request, *args, **kwargs):
        context = super(SettingsCBV, self).get_context_data(**kwargs)
        context["form"] = self.get_form()
        return render(request, "company/settings.html", context)


class LogoutCBV(LoginRequiredMixin, RedirectView):


    def get_redirect_url(self, *args, **kwargs):

        try:
            auth.logout(self.request)
            messages.success(self.request, "You have successfully logged out.")
        except Exception:
            messages.error(self.request, 
                            "Something went wrong, we could not logout your session. Please try again.")

        return reverse("login")

company/templates/company/coded_by_ryucoder.html
{% load static %}

            <div class="col-sm-6">
				<p class="text-right black">Coded By 
					<a href="http://ryucoder.in/" title="RyuCoder" target="_blank">
						<img src=" {% static 'favicon.png' %}" alt="Rockstar" class="rockstar">
						<span class="black">Ryu</span><span class="red">Coder</span>
					</a>
				</p>
			</div>

company/templates/company/common_footer.html
<footer>
    <div class="container">

        <div class="col-sm-6">
            <ul>
                <li class="black">&copy;
                    <span class="red">{% now "Y" %}</span>
                </li>
            
                {% include "company/footer_nav_links.html" with show_links=show_links %}

            </ul>
        </div>

        {% include "company/coded_by_ryucoder.html" %}

    </div>
</footer>

company/templates/company/companies_confirm_delete.html
{%  extends "company/base.html" %}

{% block title %} Confirm Deletion {% endblock %}

{% block style %}

	<style>
		
		p label{
			width: 20%;
		}

		form{
			margin-left: 6%;
			margin-top: 3%;
		}

		form input[type="submit"]{
			margin-left: 20.5%;
			margin-top: 20px;
			margin-bottom: 20px;
			width: auto;
		}

	</style>

{% endblock %}

{% block active4 %} active {% endblock %}

{% block main %} 

	<div class="main">
		
		<h1 class="blue">

			<span> Confirm Profile Deletion </span>
				
			{% include "company/welcome_username_template.html" %}

		</h1>
			
		<form action="" method="POST">
			
			{% csrf_token %}

			<p>Are you sure you want to delete your company profile? </p>

			<input class="btn btn-danger" type="submit" value="Confirm"></input>
			<a class="btn btn-default" href=" {% url 'profile' object.pk %} " title="Cancel">Cancel</a>


		</form>

	</div>

{% endblock %}

company/templates/company/dashboard.html
{%  extends "company/base.html" %}

{% load filters %}

{% block title %} Dashboard {% endblock %}
 
{% block active1 %} active {% endblock %}

{% block style %}

	<style>

	div.col-sm-3{
		/*padding: 30px;*/
	}

	.dash-menu{
		background-color: #f8f8f8;
		border: 2px solid #428bca;
		border-radius: 10px;
		text-align: center;
	}

	h2.count{
		font-size: 4em;
	}

	h2.title{
		font-size: 2em;
	}

	div.main{
		padding-bottom: 2%;
	}

	</style>

{% endblock %}

{% block main %} 

	<div class="main">

		<h1 class="blue">

			<span> Dashboard {{ objects }}</span>
				
			{% include "company/welcome_username_template.html" %}

		</h1>

		<div class="col-sm-12">
			
			<div class="col-sm-3">
				<div class="dash-menu">
					<h2 class="count">{{ count|twodigits }}</h2>
					<h2 class="title">Jobs</h2>
				</div>

			</div>

			<div class="col-sm-3">
				<div class="dash-menu">
					<h2 class="count">{{ applicants }}</h2>
					<h2 class="title">Applicants</h2>
				</div>

			</div>
			
			<div class="col-sm-3">
				<div class="dash-menu">
					<h2 class="count">{{ shortlisted }}</h2>
					<h2 class="title">Shortlisted</h2>
				</div>

			</div>

			<div class="col-sm-3">
				<div class="dash-menu">
					<h2 class="count">{{ joining }}</h2>
					<h2 class="title">Joining</h2>
				</div>

			</div>
			
		</div>

		<div class="clearfix"></div>

	</div>


{% endblock %}

company/templates/company/footer_nav_links.html
{% if show_links %}
    <li>
        <a href="#" title="Our Team">Our Team</a>
    </li>
    <li>
        <a href="#" title="FAQ">FAQ</a>
    </li>
    <li>
        <a href="#" title="Contact Us">Contact Us</a>
    </li>

{% endif %}

company/templates/company/search.html
{%  extends "company/base.html" %}

{% block title %} Search {% endblock %}

{% block active2 %} active {% endblock %}

{% block style %}

	<style>

		div.table-inside{
			padding-left: 4%;
			padding-right: 4%;
		}

		.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
		  background-color: #99ccff;
		}

		.table>tbody>tr>td{
			padding: 12px;
		}

		table thead tr th{
			text-align: center;
		}

		button{
			margin-right: 15px;
		}

		td button:nth-child(3){
			margin-right: 0;
		}

		div.col-sm-12{
			padding: 0 20px;
		}

		div.col-sm-3{
			padding: 10px;
		}

		div.col-sm-3 input{
			display: block;
			width: 100%;
			padding: 5px;
		}
		div.col-sm-3 div{
			width: 100%;
		}

		div.search button.search{
			margin-top: 20px;
			width: 100%;
		}

		div p select{
			padding: 8px;
			width: 100%;
		}

		span.count{
			/*float: right;*/
			color: #428bca;
			margin-right: 30px;
		}

		div.messages{
			width: 100%;
		}

		div.table-inside{
/*			border-bottom: 2px solid red;*/
		}
		
		.alert { 
			margin-top: 15px; 
		}

		div.paginate{
			border-top: 2px solid #428bca;
			/*padding: 0 4%;*/
			margin: 0 2%;
		}

		div.paginate div{
			display: inline;
		}

		ul.pagination li{
			float: right;
			padding-left: 0;
		}


	</style>

{% endblock %}

{% block main %} 

	<div class="main">

		<div class="search-area">
			<h1 class="blue">
			
				<span> Search Jobs </span>
				
				{% include "company/welcome_username_template.html" %}

			</h1>

			<div class="col-sm-12">
					
				<form action="" method="GET">
				
				
				<div class="col-sm-3">
					<label>Job Title</label>
					<input name="job_title" value="{{ request.GET.job_title }}" ></input>
				</div>
				<div class="col-sm-3">
					<label>Job Location</label>
					<input name="job_location" value="{{ request.GET.job_location }}" ></input>
				</div>
				<div class="col-sm-3">
					<label>Job Type</label>
					
					<p>
						<select id="id_job_type" name="job_type" required>
							<option value="-">Choose an option below</option>
							<option value="I"
								{% if request.GET.job_type == "I" %}
									{{ "selected" }}
								{% endif %}
							>Internship</option>

							<option value="T"
								{% if request.GET.job_type == "T" %}
									{{ "selected" }}
								{% endif %}
							>Temporary</option>

							<option value="C"
								{% if request.GET.job_type == "C" %}
									{{ "selected" }}
								{% endif %}
							>Contract</option>
							
							<option value="P"
								{% if request.GET.job_type == "P" %}
									{{ "selected" }}
								{% endif %}
							>Permanant</option>
							
							<option value="O"
								{% if request.GET.job_type == "O" %}
									{{ "selected" }}
								{% endif %}
							>Other</option>
						
						</select>
					</p>

				</div>
				<div class="col-sm-3">
					<label>Job Salary</label>
					<p>
						<select id="id_job_salary" name="job_salary" required>
							<option value="-">Choose an option below</option>
							<option value="ASP"
								{% if request.GET.job_salary == "ASP" %}
									{{ "selected" }}
								{% endif %}
								>As per standard
							</option>

							<option value="0"
								{% if request.GET.job_salary == "0" %}
									{{ "selected" }}
								{% endif %}
								>&lt; 1,00,000
							</option>

							<option value="1"
								{% if request.GET.job_salary == "1" %}
									{{ "selected" }}
								{% endif %}
								>1,00,000 to 2,99,999
							</option>
							
							<option value="3"
								{% if request.GET.job_salary == "3" %}
									{{ "selected" }}
								{% endif %}
								>3,00,000 to 5,99,999
							</option>
							
							<option value="6"
								{% if request.GET.job_salary == "6" %}
									{{ "selected" }}
								{% endif %}
								>6,00,000 to 9,99,999
							</option>
							
							<option value="10"
								{% if request.GET.job_salary == "10" %}
									{{ "selected" }}
								{% endif %}
								>10,00,000 +
							</option>
						
						</select>
					</p>
					
					<div class="search">
						<input class="btn btn-primary search" type="submit" value="Search Jobs">			
					</div>

				</div>
			

				</form>	
			</div>

			<div class="clearfix"></div>
		</div>

		<div class="col-xs-12">
			<div class="row">
				<div class="messages">
					{% if messages %}
						<ul class="messages text-center">
						    {% for message in messages %}
						    <li{% if message.tags %} class="col-md-8 col-md-offset-2 {{ message.tags }}"{% endif %}>{{ message }}</li>
						    {% endfor %}
						</ul>
					{% endif %}
				</div>
			</div>
		</div>

		<div class="clearfix"></div>

		<div class="listing">
			
			<h1 class="blue">Results 
			<span class="small count">
				[ Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} ]
			</span>

			</h1>
	
			<div class="table-inside">
					
				<table border="1" cellpadding="10" cellspacing="5" class="table table-hover text-center">

					<thead>
					<tr>			
						<th>Sr No</th>
						<th>Job Id</th>
						<th>Job Title</th>
						<th>Job Location</th>
						<th>Job Type</th>
						<th>Job Salary</th>
						<th>Actions</th>
					</tr>
					</thead>	
					<tbody>

					{% if count > 0 %}
						{% for x in jobs %}
							<tr>
								<td>{{ forloop.counter }}</td>
								<td>
									<a href="{% url 'jobDetail' x.id %}" title="See Job Details" target="_blank"> {{ x.job_id }} </a>
								</td>
								
								<td>{{ x.job_title }}</td>
								<td>{{ x.job_location }}</td>
								<td>{{ x.job_type }}</td>
								<td>{{ x.job_salary }}</td>

								<td>
									<a class="btn btn-warning" href="{% url 'jobEdit' x.id %}" title="Edit">Edit</a>
									<a class="btn btn-danger" href="{% url 'jobDelete' x.id %}" title="Delete">Delete</a>
								</td>					
							</tr>
						{% endfor %}

					{% else %}
					<tr>
						<td colspan="9">
							Sorry, no results to show, please modify your search parameters
						</td>
					</tr>

					{% endif %}

					</tbody>

				</table>
			</div>

		</div>

		<div class="paginate">
			<div class="pull-right">
				<ul class="pagination">

			        {% if page_obj.has_next %}
						<li>
							<a href="?page={{ page_obj.next_page_number }}&amp;
								job_title={{ request.GET.job_title }}&amp;
								job_location={{ request.GET.job_location }}&amp;
								job_type={{ request.GET.job_type }}&amp;
								job_salary={{ request.GET.job_salary }}
							">Next</a>
						</li>
			            
			        {% elif page_obj.number == page_obj.paginator.num_pages %}
						<li class="disabled" ><a href="#">Next</a></li>

			        {% endif %}

					<li class="active">
						<a href="?page={{ page_obj.number }}&amp;
							job_title={{ request.GET.job_title }}&amp;
							job_location={{ request.GET.job_location }}&amp;
							job_type={{ request.GET.job_type }}&amp;
							job_salary={{ request.GET.job_salary }}
						">Page {{ page_obj.number }}</a>

					</li>


			        {% if page_obj.has_previous %}
						<li>
							<a href="?page={{ page_obj.previous_page_number }}&amp;
								job_title={{ request.GET.job_title }}&amp;
								job_location={{ request.GET.job_location }}&amp;
								job_type={{ request.GET.job_type }}&amp;
								job_salary={{ request.GET.job_salary }}

								">Previous
							</a>
						</li>
			        {% elif page_obj.number == 1 %}
						<li class="disabled" ><a href="#">Previous</a></li>
			        {% endif %}

				</ul>
			</div>
		</div>

		<div class="clearfix"></div>
	</div>


{% endblock %}